import js from '@eslint/js';
import comments from 'eslint-plugin-eslint-comments';
import { flatConfigs as importX } from 'eslint-plugin-import-x';
import { configs as jsdocConfigs } from 'eslint-plugin-jsdoc';
import * as regexpPlugin from 'eslint-plugin-regexp';
import sortClassMembers from 'eslint-plugin-sort-class-members';
import eslintPluginUnicorn from 'eslint-plugin-unicorn';
import globals from 'globals';

import { restrictedSyntax } from './restricted-syntax.js';

/**
 * @type {import('eslint').Linter.Config[]}
 */
export const base = [
	{
		ignores: ['**/*.{ts,mts,cts,tsx}'],
	},
	{
		...js.configs.recommended,
		rules: {
			...js.configs.recommended.rules,
			'constructor-super': 0,
			'for-direction': 0,
			'getter-return': 0,
			'no-array-constructor': 0,
			'no-async-promise-executor': 0,
			'no-case-declarations': 0,
			'no-class-assign': 0,
			'no-compare-neg-zero': 0,
			'no-cond-assign': 0,
			'no-const-assign': 0,
			'no-constant-binary-expression': 0,
			'no-constant-condition': 0,
			'no-control-regex': 0,
			'no-debugger': 0,
			'no-delete-var': 0,
			'no-dupe-class-members': 0,
			'no-dupe-else-if': 0,
			'no-dupe-keys': 0,
			'no-duplicate-case': 0,
			'no-empty': 0,
			'no-empty-character-class': 0,
			'no-empty-pattern': 0,
			'no-empty-static-block': 0,
			'no-ex-assign': 0,
			'no-extra-boolean-cast': 0,
			'no-fallthrough': 0,
			'no-func-assign': 0,
			'no-global-assign': 0,
			'no-import-assign': 0,
			'no-invalid-regexp': 0,
			'no-irregular-whitespace': 0,
			'no-loss-of-precision': 0,
			'no-misleading-character-class': 0,
			'no-mixed-spaces-and-tabs': 0,
			'no-new-native-nonconstructor': 0,
			'no-nonoctal-decimal-escape': 0,
			'no-obj-calls': 0,
			'no-prototype-builtins': 0,
			'no-regex-spaces': 0,
			'no-restricted-syntax': [2, ...restrictedSyntax],
			'no-self-assign': 0,
			'no-setter-return': 0,
			'no-shadow-restricted-names': 0,
			'no-sparse-arrays': 0,
			'no-this-before-super': 0,
			'no-unexpected-multiline': 0,
			'no-unreachable': 0,
			'no-unsafe-finally': 0,
			'no-unsafe-negation': 0,
			'no-unsafe-optional-chaining': 0,
			'no-unused-labels': 0,
			'no-unused-private-class-members': 0,
			'no-unused-vars': 0,
			'no-useless-backreference': 0,
			'no-useless-catch': 0,
			'no-useless-escape': 0,
			'no-with': 0,
			'require-yield': 0,
			'use-isnan': 0,
			'valid-typeof': 0,
		},
	},
	{
		...eslintPluginUnicorn.configs.recommended,
		rules: {
			...eslintPluginUnicorn.configs.recommended.rules,
			'unicorn/catch-error-name': 0,
			'unicorn/consistent-assert': 0,
			'unicorn/consistent-date-clone': 0,
			'unicorn/consistent-destructuring': 0,
			'unicorn/consistent-empty-array-spread': 0,
			'unicorn/consistent-existence-index-check': 0,
			'unicorn/consistent-function-scoping': 0,
			'unicorn/empty-brace-spaces': 0,
			'unicorn/error-message': 0,
			'unicorn/escape-case': 0,
			'unicorn/explicit-length-check': 0,
			'unicorn/filename-case': 0,
			'unicorn/import-style': 0,
			'unicorn/new-for-builtins': 0,
			'unicorn/no-abusive-eslint-disable': 0,
			'unicorn/no-accessor-recursion': 0,
			'unicorn/no-anonymous-default-export': 0,
			'unicorn/no-array-callback-reference': 0,
			'unicorn/no-array-for-each': 0,
			'unicorn/no-array-method-this-argument': 0,
			'unicorn/no-array-reduce': 0,
			'unicorn/no-array-reverse': 0,
			'unicorn/no-array-sort': 0,
			'unicorn/no-await-expression-member': 0,
			'unicorn/no-await-in-promise-methods': 0,
			'unicorn/no-console-spaces': 0,
			'unicorn/no-document-cookie': 0,
			'unicorn/no-empty-file': 0,
			'unicorn/no-hex-escape': 0,
			'unicorn/no-immediate-mutation': 0,
			'unicorn/no-instanceof-builtins': 0,
			'unicorn/no-invalid-fetch-options': 0,
			'unicorn/no-invalid-remove-event-listener': 0,
			'unicorn/no-lonely-if': 0,
			'unicorn/no-magic-array-flat-depth': 0,
			'unicorn/no-negated-condition': 0,
			'unicorn/no-negation-in-equality-check': 0,
			'unicorn/no-nested-ternary': 0,
			'unicorn/no-new-array': 0,
			'unicorn/no-new-buffer': 0,
			'unicorn/no-null': 0,
			'unicorn/no-object-as-default-parameter': 0,
			'unicorn/no-process-exit': 0,
			'unicorn/no-single-promise-in-promise-methods': 0,
			'unicorn/no-static-only-class': 0,
			'unicorn/no-thenable': 0,
			'unicorn/no-this-assignment': 0,
			'unicorn/no-typeof-undefined': 0,
			'unicorn/no-unnecessary-array-flat-depth': 0,
			'unicorn/no-unnecessary-array-splice-count': 0,
			'unicorn/no-unnecessary-await': 0,
			'unicorn/no-unnecessary-slice-end': 0,
			'unicorn/no-unreadable-array-destructuring': 0,
			'unicorn/no-unreadable-iife': 0,
			'unicorn/no-useless-collection-argument': 0,
			'unicorn/no-useless-error-capture-stack-trace': 0,
			'unicorn/no-useless-fallback-in-spread': 0,
			'unicorn/no-useless-length-check': 0,
			'unicorn/no-useless-promise-resolve-reject': 0,
			'unicorn/no-useless-spread': 0,
			'unicorn/no-useless-switch-case': 0,
			'unicorn/no-useless-undefined': 0,
			'unicorn/no-zero-fractions': 0,
			'unicorn/number-literal-case': 0,
			'unicorn/numeric-separators-style': 0,
			'unicorn/prefer-add-event-listener': 0,
			'unicorn/prefer-array-find': 0,
			'unicorn/prefer-array-flat': 0,
			'unicorn/prefer-array-flat-map': 0,
			'unicorn/prefer-array-index-of': 0,
			'unicorn/prefer-array-some': 0,
			'unicorn/prefer-at': 0,
			'unicorn/prefer-bigint-literals': 0,
			'unicorn/prefer-blob-reading-methods': 0,
			'unicorn/prefer-class-fields': 0,
			'unicorn/prefer-classlist-toggle': 0,
			'unicorn/prefer-code-point': 0,
			'unicorn/prefer-date-now': 0,
			'unicorn/prefer-default-parameters': 0,
			'unicorn/prefer-dom-node-append': 0,
			'unicorn/prefer-dom-node-dataset': 0,
			'unicorn/prefer-dom-node-remove': 0,
			'unicorn/prefer-dom-node-text-content': 0,
			'unicorn/prefer-event-target': 0,
			'unicorn/prefer-export-from': 0,
			'unicorn/prefer-global-this': 0,
			'unicorn/prefer-includes': 0,
			'unicorn/prefer-keyboard-event-key': 0,
			'unicorn/prefer-logical-operator-over-ternary': 0,
			'unicorn/prefer-math-min-max': 0,
			'unicorn/prefer-math-trunc': 0,
			'unicorn/prefer-modern-dom-apis': 0,
			'unicorn/prefer-modern-math-apis': 0,
			'unicorn/prefer-module': 0,
			'unicorn/prefer-native-coercion-functions': 0,
			'unicorn/prefer-negative-index': 0,
			'unicorn/prefer-node-protocol': 0,
			'unicorn/prefer-number-properties': 0,
			'unicorn/prefer-object-from-entries': 0,
			'unicorn/prefer-optional-catch-binding': 0,
			'unicorn/prefer-prototype-methods': 0,
			'unicorn/prefer-query-selector': 0,
			'unicorn/prefer-reflect-apply': 0,
			'unicorn/prefer-regexp-test': 0,
			'unicorn/prefer-response-static-json': 0,
			'unicorn/prefer-set-has': 0,
			'unicorn/prefer-set-size': 0,
			'unicorn/prefer-single-call': 0,
			'unicorn/prefer-spread': 0,
			'unicorn/prefer-string-raw': 0,
			'unicorn/prefer-string-replace-all': 0,
			'unicorn/prefer-string-slice': 0,
			'unicorn/prefer-string-starts-ends-with': 0,
			'unicorn/prefer-string-trim-start-end': 0,
			'unicorn/prefer-structured-clone': 0,
			'unicorn/prefer-ternary': 0,
			'unicorn/prefer-top-level-await': 0,
			'unicorn/prefer-type-error': 0,
			'unicorn/prevent-abbreviations': 0,
			'unicorn/relative-url-style': 0,
			'unicorn/require-array-join-separator': 0,
			'unicorn/require-module-attributes': 0,
			'unicorn/require-module-specifiers': 0,
			'unicorn/require-number-to-fixed-digits-argument': 0,
			'unicorn/switch-case-braces': 0,
			'unicorn/text-encoding-identifier-case': 0,
			'unicorn/throw-new-error': 0,
		},
	},
	{
		...regexpPlugin.configs['flat/recommended'],
		rules: {
			...regexpPlugin.configs['flat/recommended'].rules,
			'no-control-regex': 0,
			'no-misleading-character-class': 0,
			'no-regex-spaces': 0,
			'prefer-regex-literals': 0,
		},
	},
	{
		...importX.recommended,
		rules: {
			...importX.recommended.rules,
			'import-x/default': 0,
			'import-x/namespace': 0,
			'import-x/no-duplicates': 0,
			'import-x/no-extraneous-dependencies': 2,
			'import-x/no-named-as-default': 0,
			'import-x/no-named-as-default-member': 0,
			'import-x/no-unresolved': 0,
			'import-x/order': [
				2,
				{
					groups: ['type', 'builtin', 'external', 'parent', 'sibling', 'index', 'object'],
					pathGroups: [
						{
							pattern: '@alias/**',
							group: 'parent',
							position: 'before',
						},
					],
					alphabetize: {
						order: 'asc',
					},
					'newlines-between': 'always',
				},
			],
		},
	},
	{
		files: [
			'*.{test,spec}.{js,mjs,json}',
			'*.config.{js,mjs,json}',
			'.*rc.{js,mjs,json}',
		],
		rules: {
			'import-x/no-extraneous-dependencies': 0,
		},
	},
	{
		...jsdocConfigs['flat/recommended'],
		rules: {
			...jsdocConfigs['flat/recommended'].rules,
			'jsdoc/check-access': 0,
			'jsdoc/check-property-names': 0,
			'jsdoc/check-tag-names': 0,
			'jsdoc/empty-tags': 0,
			'jsdoc/implements-on-classes': 0,
			'jsdoc/no-defaults': 0,
			'jsdoc/require-param': 0,
			'jsdoc/require-param-description': 0,
			'jsdoc/require-param-name': 0,
			'jsdoc/require-param-type': 0,
			'jsdoc/require-property': 0,
			'jsdoc/require-property-description': 0,
			'jsdoc/require-property-name': 0,
			'jsdoc/require-property-type': 0,
			'jsdoc/require-returns': 0,
			'jsdoc/require-returns-description': 0,
			'jsdoc/require-returns-type': 0,
			'jsdoc/require-throws-type': 0,
			'jsdoc/require-yields': 0,
			'jsdoc/require-yields-type': 0,
		},
	},
	{
		plugins: {
			comments,
		},
	},
	{
		plugins: {
			comments,
			'sort-class-members': sortClassMembers,
		},
		rules: {
			'sort-class-members/sort-class-members': [
				1,
				{
					order: [
						'[public-properties]',
						'[public-readonly-properties]',
						'[public-properties-function]',
						'[private-properties]',
						'[private-properties-function]',
						'[accessor-pairs]',
						'[getters]',
						'[setters]',
						'constructor',
						'[public-methods]',
						'[private-methods]',
						'[protedted-methods]',
						'[static-properties]',
						'[static-methods]',
						'[everything-else]',
					],
					groups: {
						'public-properties': [
							{
								type: 'property',
								kind: 'nonAccessor',
								static: false,
								private: false,
								override: false,
								readonly: false,
								sort: 'alphabetical',
							},
						],
						'public-readonly-properties': [
							{
								type: 'property',
								kind: 'nonAccessor',
								static: false,
								private: false,
								override: false,
								readonly: true,
								sort: 'alphabetical',
							},
						],
						'public-properties-function': [
							{
								type: 'property',
								propertyType: 'ArrowFunctionExpression',
								kind: 'nonAccessor',
								static: false,
								private: false,
								accessibility: 'public',
								override: false,
								sort: 'alphabetical',
							},
						],
						'private-properties': [
							{
								type: 'property',
								kind: 'nonAccessor',
								static: false,
								private: true,
								override: false,
								sort: 'alphabetical',
							},
						],
						'private-properties-function': [
							{
								type: 'property',
								propertyType: 'ArrowFunctionExpression',
								kind: 'nonAccessor',
								static: false,
								private: true,
								accessibility: 'public',
								override: false,
								sort: 'alphabetical',
							},
						],
						'public-methods': [
							{
								type: 'method',
								kind: 'nonAccessor',
								static: false,
								private: false,
								override: false,
								sort: 'alphabetical',
							},
						],
						'private-methods': [
							{
								name: '/#.+/',
								type: 'method',
								kind: 'nonAccessor',
								static: false,
								private: true,
								override: false,
								sort: 'alphabetical',
							},
						],
						'protedted-methods': [
							{
								name: '/_.+/',
								type: 'method',
								static: false,
								sort: 'alphabetical',
							},
						],
					},
					accessorPairPositioning: 'getThenSet',
				},
			],
		},
	},
	{
		languageOptions: {
			ecmaVersion: 'latest',
			globals: {
				...globals.builtin,
				...globals.nodeBuiltin,
			},
		},
	},
];
