name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
        node: [26]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: ${{ matrix.node }}

      - name: Enable Corepack and setup Yarn v4
        run: |
          corepack enable
          yarn --version

      - name: Install dependencies for Renovate/Dependabot
        if: github.actor == 'renovate[bot]' || github.actor == 'dependabot[bot]'
        run: yarn install --no-immutable

      - name: Install dependencies for normal PRs
        if: github.actor != 'renovate[bot]' && github.actor != 'dependabot[bot]'
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint:ci

      - name: Test
        run: yarn test
